### ISSUE TITLE
bigsur

### ISSUE THREAD

**Issue by lishouxian** [hackintosh-club/GA-H170MSTX-DATTO-O3#1]
这个支持bigsur吗

**Comment by WuLongMiTaoLaiYiDa** [comment]
暂时不能哦，我的big sur没能成功安装

**Comment by lishouxian** [comment]
[EFI.zip](https://github.com/rathan520/GA-H170MSTX-DATTO-O3/files/5210449/EFI.zip)
这个可以，你可以试试，但是睡眠支持不好
